### ISSUE TITLE
Bug while trying to smooth scroll the Recyclerview

### ISSUE THREAD

**Issue by sfworxco** [yarolegovich/DiscreteScrollView#112]
Hi @yarolegovich  thanks for the amazing library, we are facing a very rare issue causing the **Invalid target position** at `RecyclerViewProxy.startSmoothScroll`.  Please let us know if you've any information or idea to resolve this, we'd be happy to work on the fix if you don't have time. Thanks

* The relevant code used to `smoothScrollToPosition` the RecyclerView to to a certain position is:

```
// To auto-scroll the days layout to specified position get the selectedItem Position
val indexOfCurrentlySelectedDay = courseDaysViewModel.getIndexOfCurrentlySelectedDay()
Single.timer(500, TimeUnit.MILLISECONDS)
        .subscribe { _ ->
            if (indexOfCurrentlySelectedDay != -1 && !isFinishing) {
                courseDaysRecyclerView.smoothScrollToPosition(indexOfCurrentlySelectedDay)
            }
        }
        .autoDispose(exits)
```

* Please see the stack trace

```
Fatal Exception: java.lang.IllegalArgumentException: Invalid target position
       at android.support.v7.widget.RecyclerView$LayoutManager.android.support.v7.widget.RecyclerView$SmoothScroller.start(SourceFile:14377)
       at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.com.yarolegovich.discretescrollview.RecyclerViewProxy.startSmoothScroll(SourceFile:40102)
       at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.startSmoothPendingScroll(SourceFile:508)
       at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.smoothScrollToPosition(SourceFile:365)
       at android.support.v7.widget.RecyclerView.smoothScrollToPosition(SourceFile:1700)
       at co.insight.android.courses.view.days.ActivityCourseDays$initUi$8$1.accept$632b64c(SourceFile:1230)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(SourceFile:63)
       at io.reactivex.internal.operators.single.SingleTimer$TimerDisposable.run(SourceFile:56)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:38)
       at io.reactivex.internal.schedulers.ScheduledDirectTask.call(SourceFile:26)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by yarolegovich** [comment]
Most probably this issue is fixed in 1.4.8.

P.S. Sorry, I bet you're not interested in this fix already.
