### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by wzxx** [yarolegovich/DiscreteScrollView#129]
Hi there,
     there is an ANR when I use DiscreteScrollView.

     There is the log:

"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 obj=0x74faf5a0 self=0xf3bb7400
  | sysTid=27669 nice=-4 cgrp=default sched=0/0 handle=0xf70e4de4
  | state=R schedstat=( 344540533785 291136814168 585911 ) utm=30595 stm=3859 core=5 HZ=100
  | stack=0xff442000-0xff444000 stackSize=8MB
  | held mutexes= "mutator lock"(shared held)
  at com.yarolegovich.discretescrollview.DSVOrientation$HorizontalHelper.shiftViewCenter(DSVOrientation.java:76)
  at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.a(DiscreteScrollLayoutManager.java:214)
  at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.e(DiscreteScrollLayoutManager.java:194)
  at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.c(DiscreteScrollLayoutManager.java:122)
  at android.support.v7.widget.RecyclerView.O(RecyclerView.java:3812)
  at android.support.v7.widget.RecyclerView.r(RecyclerView.java:3529)
  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
  at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
  at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
  at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2825)
  at android.view.View.layout(View.java:16947)
  at android.view.ViewGroup.layout(ViewGroup.java:5711)
  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2551)
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2254)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1325)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6756)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
  at android.view.Choreographer.doCallbacks(Choreographer.java:713)
  at android.view.Choreographer.doFrame(Choreographer.java:648)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
  at android.os.Handler.handleCallback(Handler.java:815)
  at android.os.Handler.dispatchMessage(Handler.java:104)
  at android.os.Looper.loop(Looper.java:207)
  at android.app.ActivityThread.main(ActivityThread.java:5856)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)

And what I want to ask is that what kind of scenes may cause this problem?
Thanks so much

**Comment by raghunaikbadde** [comment]
IS this issue resolved?
