### ISSUE TITLE
`java.lang.IllegalArgumentException` on calling `scrollToPosition()`

### ISSUE THREAD

**Issue by gsanskar** [yarolegovich/DiscreteScrollView#142]
Getting the following error when `setScrollToPosition(noOfItems)` is called:

`09-25 15:57:16.290 28287-28287/com.developit.pebbles E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.developit.pebbles, PID: 28287
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.developit.pebbles/com.developit.pebblestv.activity.HomeActivity}: java.lang.IllegalArgumentException: target position out of bounds: position=3, itemCount=0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalArgumentException: target position out of bounds: position=3, itemCount=0
        at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.checkTargetPosition(DiscreteScrollLayoutManager.java:724)
        at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.smoothScrollToPosition(DiscreteScrollLayoutManager.java:363)
        at android.support.v7.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1700)
        at com.developit.pebblestv.activity.HomeActivity.onCreate(HomeActivity.java:80)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
`

**My inference:** All the items aren't populated when the function is called. If that's the case, May I please know how can I listen to the event when all the items in the adapter have been populated?

Thanks!

**Comment by gildor** [comment]
We have the same issue with `smoothScrollToPosition`. We have code that updates adapter, calls notifyDataSetChanged, and then calls scrollToPosition, but looks that RecyclerView.State is not updated yet and we don't have access to the state to understand how many items rendered there and avoid the crash.

We probably should reconsider this check (remove or make optional) and ignore such scroll request.

For now, we try to wrap scrollToPosition to View.post to fix this crash

**Comment by kagile** [comment]
@gildor Will this ever be fixed?

**Comment by gildor** [comment]
@kagile Why do you asking me? :)
We now use own fork of DiscreteScrollView where we just removed this check (and yeah, it breaks scrolling, but it's already better than crash). Now I believe this is some issue of DiscreteScrollLayoutManager, I didn't check properly how to fix it, the problem that even `post` doesn't help sometimes in this case, RecyclerView state has not updated even after Handler.post

But I still not sure, maybe the author have some comments about this

**Comment by terranology** [comment]
The component is doing too much work, so post runnable solved this issue for me.
item_picker.post(new Runnable() {
                            @Override
                            public void run() {
                                item_picker.smoothScrollToPosition(item_picker.getCurrentItem() + 1);
                            }
                        });

**Comment by gildor** [comment]
@terranology You right, `post()` helps a bit, but it still not a solution, just make this error not so often, but reproducible.

**Comment by vararg** [comment]
Same problem here. I tried to debug and figure out what goes wrong, but it's really hard.
Looks like event with data updates (after notifyItemInserted) succesfully published to AdapterHelper(inner entity of RecyclerView) but changes will be processed to RecyclerView.State some time later. 

**Still not 100% sure. Will check it later.** 
But it can be workaround for that. Not best way, but also not so bad.
In DiscreteScrollLayoutManager we have few methods for updating onItemsAdded/onItemsRemoved/onItemsChanged. They triggers when AdapterHelper start his work and RecyclerView's State in correct position. So we can add listener with scroll invocation.
