### ISSUE TITLE
Scroll to Specific Element 

### ISSUE THREAD

**Issue by logicgupta** [yarolegovich/DiscreteScrollView#197]
java.lang.IllegalArgumentException: target position out of bounds: position=1, itemCount=0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3307)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3446)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7550)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalArgumentException: target position out of bounds: position=1, itemCount=0
        at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.checkTargetPosition(DiscreteScrollLayoutManager.java:742)
        at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.smoothScrollToPosition(DiscreteScrollLayoutManager.java:365)
        at androidx.recyclerview.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1790)

**Comment by janvalji** [comment]
same +1 @yarolegovich

**Comment by muhammad-farhan-bakht** [comment]
I am facing the same problem If anyone knows the workaround or solution please Share.
@logicgupta  @gordonfreemanix  @yarolegovich

**Comment by muhammad-farhan-bakht** [comment]
I have fixed this problem and sharing my solution here so if anyone who also faced this problem can work with it.

```
public void smoothScrollToUserSelectedPosition(DiscreteScrollView discreteScrollView, int imgIndex) {
        try {
            final RecyclerView.Adapter<?> adapter = discreteScrollView.getAdapter();
            int destination = imgIndex;
            if (adapter instanceof InfiniteScrollAdapter) {
                destination = ((InfiniteScrollAdapter<?>) adapter).getClosestPosition(destination);
            }
            discreteScrollView.smoothScrollToPosition(destination);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

**Call Like this:**
```
new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                smoothScrollToUserSelectedPosition(discreteScrollView, imgIndex);
            }
        }, 100);
```
