### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by muratdoglu** [yarolegovich/DiscreteScrollView#42]
java.lang.IndexOutOfBoundsException: Invalid item position -1(-1). Item count:6 
i dont understand. thank you

**Comment by muratdoglu** [comment]
@yarolegovich

**Comment by yarolegovich** [comment]
First of all, it is always helpful to see the full stacktrace. Second, I guess the problem is somewhere in your adapter.

**Comment by muratdoglu** [comment]
i want to pull to refresh data,  
mutfakDynamicListeObjectArrayList.clear(); 
 mutfakDynamicListeAdapter.notifyDataSetChanged();
after, this crash @yarolegovich  

java.lang.IndexOutOfBoundsException: Invalid item position -1(-1). Item count:3
                                                                 at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5466)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                 at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                 at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.layoutView(DiscreteScrollLayoutManager.java:188)
                                                                 at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.fill(DiscreteScrollLayoutManager.java:152)
                                                                 at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.onLayoutChildren(DiscreteScrollLayoutManager.java:103)
                                                                 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                 at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                 at android.view.View.measure(View.java:19857)

**Comment by muratdoglu** [comment]
private void layoutView(RecyclerView.Recycler recycler, int position, Point viewCenter) {
        View v = detachedCache.get(position);
        if (v == null) {
            **v = recycler.getViewForPosition(position);**
            addView(v);
            measureChildWithMargins(v, 0, 0);
            layoutDecoratedWithMargins(v,
                    viewCenter.x - childHalfWidth, viewCenter.y - childHalfHeight,
                    viewCenter.x + childHalfWidth, viewCenter.y + childHalfHeight);
        } else {
            attachView(v);
            detachedCache.remove(position);
        }
    }
