### ISSUE TITLE
notifyDataSetChanged()

### ISSUE THREAD

**Issue by xdewnik** [yarolegovich/DiscreteScrollView#75]
Getting nullpointer ,when trying to `adepter.notifyDataSetChanged()`

`Attempt to invoke virtual method 'void com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.scrollToPosition(int)' on a null object reference`

**Comment by yarolegovich** [comment]
Post a complete stacktrace please, so I can know where the exception is thrown.

**Comment by yarolegovich** [comment]
I will appreciate if you add a failing test case [here](https://github.com/yarolegovich/DiscreteScrollView/blob/master/library/src/androidTest/java/com/yarolegovich/discretescrollview/DataSetModificationTest.java).

**Comment by blackadmin** [comment]
Me facing the same issue

```
EventBus: Could not dispatch event: class com.cloudblocks.android.user.EventType to subscribing class class com.cloudblocks.android.user.ui.devicegroup.FragmentDeviceGroupList
                                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'void com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.scrollToPosition(int)' on a null object reference
                                                                                  at com.yarolegovich.discretescrollview.InfiniteScrollAdapter.resetRange(InfiniteScrollAdapter.java:129)
                                                                                  at com.yarolegovich.discretescrollview.InfiniteScrollAdapter.access$100(InfiniteScrollAdapter.java:13)
                                                                                  at com.yarolegovich.discretescrollview.InfiniteScrollAdapter$DataSetChangeDelegate.onChanged(InfiniteScrollAdapter.java:141)
                                                                                  at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11566)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6788)
                                                                                  at com.cloudblocks.android.user.ui.devicegroup.FragmentDeviceGroupList.onEventGetDeviceGroupList(FragmentDeviceGroupList.java:190)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
                                                                                  at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:434)
                                                                                  at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:411)
                                                                                  at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:384)
                                                                                  at org.greenrobot.eventbus.EventBus.post(EventBus.java:265)
                                                                                  at com.cloudblocks.android.core.manager.DeviceGroupManager$1.onResponse(DeviceGroupManager.java:62)
                                                                                  at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6422)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
